<?php
include "queue.php";
$object = new Queue();
?>
<head>
    <style>
        .active {
            border: 1px solid black;
            background-color: grey;
        }
        .inactive {
            border: 1px solid black;
            background-color: pink;
        }
        th {
            font-size: 25px;
        }
    </style>
</head>
<?php
foreach($object->getSplObject() as $key => $value) {
    var_dump($key, $value);
}
?>
<table width="100%" style="td:first{color:red}">
    <colgroup>
        <?php foreach ($object->getSplObject() as $key => $value) : ?>
            <col width="<?php echo 100/$object->getSplObject()->count() . '%' ?>"/>
        <?php endforeach ?>
        <col width="100%"/>
    </colgroup>
    <tr>
        <?php foreach ($object->getSplObject() as $key => $value) : ?>
            <th><?php echo $key ?></th>
        <?php endforeach ?>
    </tr>
    <tr>
        <?php foreach ($object->getSplObject() as $key => $value) : ?>
            <td class=<?php echo ($object->getPointer() == $value) ? "active" : "inactive" ?> height="60px" align="center"><?php echo $value ?></td>
        <?php endforeach ?>
    </tr>
</table>
</br></br></br>
<form method="post">
    <input type="submit" name="prepend" value="add Element"></br></br>
    <?php if (!$object->isObjectEmpty()) : ?>
        <input type="submit" name="removeFirst" value="get Element">
        </br></br>
    <?php endif ?>
</form>